# Generated by Django 6.0.2 on 2026-02-21 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DroneModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_file', models.CharField(blank=True, max_length=255, null=True)),
                ('pdf_file', models.CharField(blank=True, max_length=255, null=True)),
                ('vehicle_type', models.CharField(blank=True, max_length=100, null=True)),
                ('build_class', models.CharField(blank=True, max_length=100, null=True)),
                ('relations', models.JSONField(blank=True, default=dict)),
            ],
        ),
    ]
