# Generated by Django 6.0.2 on 2026-02-21 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0002_dronemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='image_file',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='component',
            name='manual_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
