# Generated by Django 6.0.2 on 2026-02-25 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0003_component_image_file_component_manual_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('estimated_time_minutes', models.IntegerField(default=60)),
                ('drone_class', models.CharField(blank=True, max_length=50)),
                ('thumbnail', models.CharField(blank=True, max_length=500)),
                ('required_tools', models.JSONField(blank=True, default=list)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('drone_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guides', to='components.dronemodel')),
            ],
        ),
        migrations.CreateModel(
            name='BuildGuideStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('safety_warning', models.TextField(blank=True)),
                ('reference_image', models.CharField(blank=True, max_length=500)),
                ('stl_file', models.CharField(blank=True, max_length=500)),
                ('betaflight_cli', models.TextField(blank=True)),
                ('step_type', models.CharField(choices=[('assembly', 'Assembly'), ('soldering', 'Soldering'), ('firmware', 'Firmware'), ('3d_print', '3D Print'), ('inspection', 'Inspection')], default='assembly', max_length=50)),
                ('estimated_time_minutes', models.IntegerField(default=5)),
                ('required_components', models.JSONField(blank=True, default=list)),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='components.buildguide')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('guide', 'order')},
            },
        ),
        migrations.CreateModel(
            name='BuildSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=50, unique=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('current_step', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='in_progress', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('component_checklist', models.JSONField(blank=True, default=dict)),
                ('builder_name', models.CharField(blank=True, max_length=255)),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='components.buildguide')),
            ],
        ),
        migrations.CreateModel(
            name='StepPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='build_photos/%Y/%m/%d/')),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='components.buildsession')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='components.buildguidestep')),
            ],
        ),
    ]
