# Generated by Django 6.0.2 on 2026-03-06 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0004_buildguide_buildguidestep_buildsession_stepphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildsession',
            name='step_notes',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
