# Generated by Django 6.0.2 on 2026-03-06 03:17

from django.db import migrations, models


def migrate_reference_image_to_media(apps, schema_editor):
    """Convert existing reference_image strings to media JSON arrays."""
    Step = apps.get_model('components', 'BuildGuideStep')
    for step in Step.objects.all():
        if step.reference_image and not step.media:
            step.media = [{"type": "image", "url": step.reference_image, "caption": ""}]
            step.save(update_fields=['media'])


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0005_buildsession_step_notes'),
    ]

    operations = [
        # 1. Add the new media field
        migrations.AddField(
            model_name='buildguidestep',
            name='media',
            field=models.JSONField(blank=True, default=list),
        ),
        # 2. Copy reference_image data into media
        migrations.RunPython(migrate_reference_image_to_media, migrations.RunPython.noop),
        # 3. Remove old field
        migrations.RemoveField(
            model_name='buildguidestep',
            name='reference_image',
        ),
    ]
