# Generated by Django 6.0.2 on 2026-03-06 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0006_replace_reference_image_with_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildsession',
            name='component_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='buildsession',
            name='guide_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='buildsession',
            name='step_timing',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='stepphoto',
            name='sha256',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.CreateModel(
            name='BuildEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('session_started', 'Session Started'), ('session_completed', 'Session Completed'), ('session_abandoned', 'Session Abandoned'), ('step_started', 'Step Started'), ('step_completed', 'Step Completed'), ('photo_captured', 'Photo Captured'), ('note_saved', 'Note Saved'), ('checklist_updated', 'Checklist Updated')], max_length=30)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('step_order', models.IntegerField(blank=True, null=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='components.buildsession')),
            ],
            options={
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['session', 'timestamp'], name='components__session_32b768_idx')],
            },
        ),
    ]
