# Generated by Django 6.0.2 on 2026-03-08 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0007_build_audit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='buildguidestep',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='buildguidestep',
            name='title',
            field=models.CharField(default='Untitled', max_length=255),
        ),
    ]
