# Generated by Django 6.0.2 on 2026-03-08 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0008_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildevent',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='components.buildsession'),
        ),
        migrations.AlterField(
            model_name='buildsession',
            name='guide',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='components.buildguide'),
        ),
        migrations.AlterField(
            model_name='stepphoto',
            name='step',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='components.buildguidestep'),
        ),
    ]
