# Generated by Django 6.0.2 on 2026-03-08 18:38

import components.upload_utils
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0009_data_integrity_fixes'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuideMediaFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=components.upload_utils.guide_media_upload_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=100)),
                ('file_size', models.PositiveIntegerField()),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='components.buildguide')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
